# Change these first
owner: foorumico # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Foorumi.co
    url: https://foorumi.co
  - name: Foorumi.co keskustelu
    url: https://keskustelu.foorumi.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.foorumi.co
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Foorumi.co Status
  introTitle: "**Foorumi.co** status"
  introMessage: T채ll채 sivulla voitte n채hd채 Foorumi.co palvelun eri tilat
  navbar:
    - title: Status
      href: /
    - title: Foorumi.co
      href: https://foorumi.co

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
