# Change these first
owner: foorumico # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Foorumi.co
    url: https://foorumi.co
  - name: Foorumi.co keskustelu
    url: https://keskustelu.foorumi.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.foorumi.co
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Foorumi.co Status
  introTitle: "**Foorumi.co** status"
  introMessage: Tällä sivulla voitte nähdä Foorumi.co palvelun eri tilat
  navbar:
    - title: Status
      href: /
    - title: Foorumi.co
      href: https://foorumi.co

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  url: "URL"
  status: "Tila"
  history: "Historia"
  responseTime: "Vasteaika"
  uptime: "Ylhäälläoloaika"
  up: "Ylhäällä"
  degraded: "Heikentynyt"
  down: "Alhaalla"
  responseTimeGraphAlt: "Vasteaika graafi"
  ms: "ms"
  responseTimeDay: "24h vasteaika"
  responseTimeWeek: "7 päivän vasteaika"
  responseTimeMonth: "30 päivän vasteaika"
  responseTimeYear: "1 vuoden vasteaika"
  uptimeDay: "24h ylhäälläoloaika"
  uptimeWeek: "7 päivän ylhäälläoloaika"
  uptimeMonth: "30 päivän ylhäälläoloaika"
  uptimeYear: "1 vuoden ylhäälläoloaika"
  liveStatus: "Live tila"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "Kaikki järjestelmät toiminnassa"
  degradedPerformance: "Heikentynyt toiminta"
  completeOutage: "Täydellinen katkos"
  partialOutage: "Osittainen katkos"
  activeIncidents: "Aktiiviset tapahtumat"
  incidentReport: "Tapahtuma #$NUMBER raportti →"
  activeIncidentSummary: "Avattu $DATE ja sisältää $POSTS viestiä"
  incidentTitle: "Tapahtuman $NUMBER tiedot"
  incidentDetails: "Tapahtuman tiedot"
  incidentFixed: "Korjattu"
  incidentOngoing: "Meneillään"
  incidentOpenedAt: "Avattu"
  incidentClosedAt: "Suljettu"
  incidentViewOnGitHub: "Katso ja seuraa GitHubissa"
  incidentCommentSummary: "Julkaistu $DATE ($AUTHOR)"
  incidentBack: "← Takaisin tapahtumiin"
  pastIncidents: "Menneet tapahtumat"
  pastIncidentsResolved: "Ratkaistu $MINUTES minuutissa ja sisältää $POSTS viestiä"
  overallUptime: "Ylhäälläoloaika: $UPTIME"
  overallUptimeTitle: "Ylhäälläoloaika"
  averageResponseTime: "Keskimääräinen vasteaika: $TIMEms"
  averageResponseTimeTitle: "Keskimääräinen vasteaika"
  sevelDayResponseTime: "7 päivän vasteaika"
  responseTimeMs: "Vasteaika (ms)"
  loading: "Ladataan"
  navGitHub: GitHub
  footer: "Tämä sivu on [avointa lähdeköödi]($REPO), powered by [Upptime](https://upptime.js.org)"
  rateLimitExceededTitle: Rate limit exceeded
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: "Tapahtui virhe"
  errorIntro: "Tapahtui virhe, kun yritimme hakea viimeisimmän tilan tietoja."
  errorText: "Voit yrittää uudelleen hetken kuluttua."
  errorHome: "Mene etusivulle"
  pastScheduledMaintenance: "Menneet ajastetut huollot"
  scheduledMaintenance: "Ajastettu huolto"
  scheduledMaintenanceSummaryStarted: "Alkoi $DATE ja kesti $DURATION minuuttia"
  scheduledMaintenanceSummaryStarts: "Alkaa $DATE ja kestää $DURATION minuuttia"
  startedAt: "Alkoi"
  startsAt: "Alkaa"
  duration: "Kesto"
  durationMin: "$DURATION minuuttia"
  incidentCompleted: "Valmistunut"
  incidentScheduled: "Ajastettu"